### ISSUE TITLE
Implicit search report NPE for scala 2.10.4

### ISSUE THREAD

**Issue by jilen** [scalamacros/paradise#45]
See full stack [here](https://gist.github.com/jilen/497b4ba60d08d23b9f8d)

```
[error] java.lang.NullPointerException
[error]     at org.scalamacros.paradise.typechecker.Implicits$ParadiseImplicitSearch.isImpossibleSubType(Implicits.scala:367)
[error]     at org.scalamacros.paradise.typechecker.Implicits$ParadiseImplicitSearch.isPlausiblySubType(Implicits.scala:362)

[error]     at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
[error]     at scala.collection.immutable.List.foldLeft(List.scala:84)
```

**Comment by xeno-by** [comment]
Thanks for the report! Could you provide reproduction instructions?

**Comment by jilen** [comment]
``` scala
def encoderImpl[T: c.WeakTypeTag](c: Context): c.Expr[DatumEncoder[T]]  = {
    import c.universe._
    val tpe = weakTypeOf[T]
    val tree =  weakTypeOf[T].declarations.collect {
      case m: MethodSymbol if m.isCaseAccessor => m
    }


    val pairs = tree.foldLeft(q"Seq[Datum.AssocPair]()") {
      case (pairsTree, accessorTree) =>
        val valueType = accessorTree.returnType
        val encoderType = tq"DatumEncoder[$valueType]"
        val encoder = c.inferImplicitValue(encoderType.tpe)
        if(encoder == EmptyTree) {
          c.abort(c.enclosingPosition, s"No implicit encoder for ${encoderType}")
        }
        val value = q"t.$accessorTree"
        q"$pairsTree :+ Datum.AssocPair(Some(accessorTree.name), $encoder.encode($value) )"
    }

    val encodedDatum = q"Datum(`type` = Some(Datum.DatumType.R_OBJECT), rObject = $pairs )"
    val method = q"def encode(t: $tpe) = $encodedDatum"

    c.Expr[DatumEncoder[T]](q"""
     import srethink.protocol._
     new DatumEncoder[$tpe] {
       def encode(t: $tpe) = $method
     }""")
  }
```

**Comment by xeno-by** [comment]
Would it be possible to provide a self-contained example? It would be ideal if that was a standalone sbt project published e.g. at github.

**Comment by jilen** [comment]
https://github.com/jilen/srethink/blob/quasiquotes/src/main/scala/srethink/core/codec/CodecsMacro.scala Look at this and this https://travis-ci.org/jilen/srethink

**Comment by xeno-by** [comment]
Thank you! I'll try to take a look one of these days.

**Comment by jilen** [comment]
I try to print the infer information by adding following

``` scala
 override def inferImplicit(tree: Tree, pt: Type, reportAmbiguous: Boolean, isView: Boolean, context: Context, saveAmbiguousDivergent: Boolean, pos: Position): SearchResult = {
    println(s"infering ${tree} ${pt}" )
```

And found it prints `infering <empty> null` 

The following is how I am trying to infer implicit 

``` scala
 val valueType = accessorTree.returnType
 val encoderType = tq"DatumEncoder[$valueType]"
 val encoder = c.inferImplicitValue(encoderType.tpe)
```

Is that wrong ?

**Comment by xeno-by** [comment]
Oh I see. It's simpler than I thought. You need to typecheck `encoderType` before you can use its `tpe`. Something along the lines of:

```
val encoderType = tq"DatumEncoder[$valueType]"
val "val x: $typedEncoderType = ???" = c.typeCheck(q"val x: $encoderType = ???")
val encoder = c.inferImplicitValue(typedEncoderType.tpe)
```
