### ISSUE TITLE
c.typecheck leads to a weird NPE

### ISSUE THREAD

**Issue by xeno-by** [scalamacros/paradise#50]
```
import scala.language.experimental.macros
import scala.reflect.macros.whitebox.Context

class foo extends scala.annotation.StaticAnnotation

class bar extends scala.annotation.StaticAnnotation {
  def macroTransform(annottees: Any*): Any = macro Macros.impl
}

object Macros {
  def impl(c: Context)(annottees: c.Expr[Any]*): c.Expr[Any] = {
    import c.universe._
    c.typecheck(annottees(0).tree.duplicate)
    c.Expr[Any](Block(annottees.map(_.tree).toList, Literal(Constant(()))))
  }
}
```

```
trait A

@bar
class B(@foo val a: A)

class C
```

```
15:57 ~/Projects/Paradise211x/sandbox/src/main/scala (2.11.x)$ ks
>>>> new bar().macroTransform(class B extends scala.AnyRef {
  @new foo() <paramaccessor> val a: A = _;
  def <init>(@new foo() a: A) = {
    super.<init>();
    ()
  }
})
error: java.lang.NullPointerException
    at scala.reflect.internal.Scopes$Scope.unlink(Scopes.scala:195)
    at scala.reflect.internal.Scopes$Scope.unlink(Scopes.scala:215)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter$$anonfun$destroy$1.apply(Namers.scala:301)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter$$anonfun$destroy$1.apply(Namers.scala:299)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.destroy(Namers.scala:299)
    at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:394)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:320)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:310)
    at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:338)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:322)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:310)
    at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:338)
    at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:133)
    at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:126)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expandMacroAnnotations(Expanders.scala:126)
    at org.scalamacros.paradise.typechecker.Expanders$$anon$1.expandMacroAnnotations(Expanders.scala:14)
    at org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterStats(AnalyzerPlugins.scala:32)
    at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:450)
    at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:449)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
    at scala.collection.immutable.List.foldLeft(List.scala:83)
    at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsEnterStats(AnalyzerPlugins.scala:449)
    at scala.tools.nsc.Global$$anon$1.pluginsEnterStats(Global.scala:439)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4912)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:410)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1542)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1537)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1644)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:51)
    at scala.tools.nsc.Driver.main(Driver.scala:64)
    at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.NullPointerException
    at scala.reflect.internal.Scopes$Scope.unlink(Scopes.scala:195)
    at scala.reflect.internal.Scopes$Scope.unlink(Scopes.scala:215)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter$$anonfun$destroy$1.apply(Namers.scala:301)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter$$anonfun$destroy$1.apply(Namers.scala:299)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.destroy(Namers.scala:299)
    at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:394)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:320)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:310)
    at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:338)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:322)
    at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:310)
    at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:338)
    at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:133)
    at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:126)
    at scala.collection.immutable.List.flatMap(List.scala:327)
    at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expandMacroAnnotations(Expanders.scala:126)
    at org.scalamacros.paradise.typechecker.Expanders$$anon$1.expandMacroAnnotations(Expanders.scala:14)
    at org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterStats(AnalyzerPlugins.scala:32)
    at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:450)
    at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:449)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
    at scala.collection.immutable.List.foldLeft(List.scala:83)
    at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsEnterStats(AnalyzerPlugins.scala:449)
    at scala.tools.nsc.Global$$anon$1.pluginsEnterStats(Global.scala:439)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4912)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:410)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1542)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1537)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1644)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:51)
    at scala.tools.nsc.Driver.main(Driver.scala:64)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by xeno-by** [comment]
The workaround is to explicitly define a companion for `class B`

**Comment by bar** [comment]
Please don't use my name to document your code, thanks!

**Comment by rjean-gilles** [comment]
A better work around is to generate an empty private companion for `class B` in the macro. It prevents the NPE too, and does not require to uglify client code.

**Comment by xeno-by** [comment]
I've merged this issue into https://github.com/scalamacros/paradise/issues/75 and will close this issue now. If this is a blocker for you, please let me know, and we'll think of something.
